//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSharpHl7Parser.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSharpHl7Parser.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSH|^~\&amp;|ProPM|Dermatology Associates|Ellkay|Ellkay|20140403131443||ADT^A08|35750-2014040313144342510|P|2.3|||NE|NE
        ///EVN|A08|20140403131443||01|nnewton^Newton^Nikki
        ///PID|1||35750||NEWTON^NICOLE^M||19810901|F||White|2651 PEYTON WAY^^PANAMA CITY^FL^32405||(850)832-5912^^^^^850^8325912|(850)522-5000^^^^^850^5225000|^English|||35750||||Hispanic / Latino
        ///PV1|1|R|||||CRK^Kovaleski^Charles^R^MD^^^^&amp;E15788&amp;UPIN|CRK^Kovaleski^Charles^R^MD^^^^&amp;E15788&amp;UPIN|^^^^^^^^&amp;&amp;UPIN
        ///GT1|1|35750|NEWTON^NICOLE^M||2651 PEYTON WAY^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleMessages1 {
            get {
                return ResourceManager.GetString("MultipleMessages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSH|^~\&amp;|MM^ModernizingMedicine|derm^Barrington Park Dermatological Associates |LKBRIDGE^Ellkay|ELLKAY^Barrington Park Dermatological Associates |20150811200521||DFT^P03|20150811200521890|P|2.5.1
        ///EVN|P03|20150811200521
        ///PID||335544|911525532||Aaron^Maya^^^||19780827|F|||||||||||902917322
        ///PV1|1||10^^^Primary Facility^^^^^Primary Facility||||^Cane^Daniel^^MD^||||||||||||127206|||||||||||||||||||||||||||||||127206
        ///FT1|1|||20150811|20150811200521|CG|AFAPE^^EMA|AFA Chemical Peel||1|120.0^USD|||||10^^^Primary  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSH|^~\&amp;|ProPM|Dermatology Associates|Ellkay|Ellkay|20140403131443||ADT^A08|35750-2014040313144342510|P|2.3|||NE|NE
        ///EVN|A08|20140403131443||01|nnewton^Newton^Nikki
        ///PID|1||35750||NEWTON^NICOLE^M||19810901|F||White|2651 PEYTON WAY^^PANAMA CITY^FL^32405||(850)832-5912^^^^^850^8325912|(850)522-5000^^^^^850^5225000|^English|||35750||||Hispanic / Latino
        ///PV1|1|R|||||CRK^Kovaleski^Charles^R^MD^^^^&amp;E15788&amp;UPIN|CRK^Kovaleski^Charles^R^MD^^^^&amp;E15788&amp;UPIN|^^^^^^^^&amp;&amp;UPIN
        ///GT1|1|35750|NEWTON^NICOLE^M||2651 PEYTON WAY^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample2 {
            get {
                return ResourceManager.GetString("Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSH|^~\&amp;|MIK-AIG^MIK-AIG^GUID||EllkaySched^EllkaySched^GUID||20151211171243||SIU^S14|00D78E9D-85BD-4b8d-A9C0-E45FC1C42364|P|2.3||||NE
        ///SCH|00291822501|||||||FU^FOLLOW UP|10|MIN|^^^201702081000|||||||||ELUNA|||||PENDING
        ///PID|1||70761^1|603319|KEMPNER^LINN^J||19460304|M||3|10 IRON HORSE ROAD^^LITTLE ROCK^AR^72211||(501)786-2070^^^L.JKEMPNER@YAHOO.COM||ENG^ENGLISH|M|||432846391|||N^N
        ///PV1|1
        ///RGS|1
        ///AIL|1||24^PINNACLE DERMATOLOGY CLINIC
        ///AIP|1||126^MARTIN^TERRI^L|7
        ///NTE|1||6 MONTH F/U
        ///ZAS|1|1||||||||||||0|0|0| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample3 {
            get {
                return ResourceManager.GetString("Sample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSH|^~\&amp;|PYXISCC||PYXISCC|PRIME|20160915144327||SIU^S12|3650|P|2.3.1|        ///SCH|1264179|1264179|||1264179|APPOINTMENT|FOLLOW UP|FOLLOW UP|15|m|^^^201609211445|||||16||||16|||||Booked^Booked^        ///NTE|||MB        ///PID||051915|160970|008|AMOS^ERICA-8^|1|19830322|F|||2351 WASHINGTON ST # 103^^SAN FRANCISCO^CA^941151910||(405) 659-0006|||Single|||447-84-5313||||        ///PV1|1|O||||00^EpsteinTuffanelli|008^NG^JUDY^        ///DG1|1|ICD9|436^315||||||||||||        ///GT1|1|160970|AMOS^ERICA-8^||2351 WASHINGTON ST # 103^^SAN FRANCISCO^CA^941151910|(405) 659-000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample4 {
            get {
                return ResourceManager.GetString("Sample4", resourceCulture);
            }
        }
    }
}
